### ISSUE TITLE
Make Alix available for Firefox

### ISSUE THREAD

**Issue by GuillaumeAmat** [ireade/alix#6]
Both Chrome and Firefox support WebExtensions : https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

Can you consider it?

**Comment by ireade** [comment]
Hi @GuillaumeAmat ! Yes it's definitely on my list of things to do.

**Comment by GuillaumeAmat** [comment]
Great! Thank you :)

**Comment by josephrexme** [comment]
@ireade this may be useful in creating this without a hassle https://www.emailthis.me/open-source/extension-boilerplate

**Comment by ireade** [comment]
Thanks @bl4ckdu5t I'll check that out

**Comment by ireade** [comment]
@GuillaumeAmat This is now done! Check the README for links to the Firefox AddOn

**Comment by GuillaumeAmat** [comment]
Great! I'll test that ASAP :)
Thank you very much!
